apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: nok-base
type: Opaque

stringData:
  client-secret: "sxV7tuV2qL8Lse1Sxkecwn2OrAxC39js"

  cookie-secret: "0123456789abcdef0123456789abcdef"
