apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-proxy-headers
  namespace: nok-base
data:
  X-Forwarded-Proto: http
  X-Forwarded-Host: bng.nok.local:8080
  X-Forwarded-Port: "8080"
  X-Forwarded-Prefix: /auth
