apiVersion: v1
kind: Secret

metadata:
  name: keycloak-postgres-secret
  namespace: nok-bng

type: Opaque

stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak123
